#ifndef CONSOLE_COLOR_H
#define CONSOLE_COLOR_H

#include <windows.h>

static inline void set_color(WORD attrs) {
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), attrs);
}

#define COLOR_DEFAULT   (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)
#define COLOR_TIP       (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define COLOR_TITLE     (FOREGROUND_RED | FOREGROUND_INTENSITY)
#define COLOR_MAIN_MENU (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY)
#define COLOR_MENU      (FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY)
#define COLOR_SUCCESS   (FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define COLOR_ERROR     (FOREGROUND_RED | FOREGROUND_INTENSITY)
#endif